### ISSUE TITLE
Dependency on Frameworkbundle 2.3/3.0 make upgrade to Symfony 4.x impossible

### ISSUE THREAD

**Issue by kszyma** [Basster/legacy-bridge-bundle#2]
Hi :)

When i try to upgrade our appilication from symfony 3.4 to 4.1 iget the following message from composer:

Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - basster/legacy-bridge-bundle 1.0.1 requires symfony/framework-bundle ~2.3|~3.0

It would be cool if you can fix this :)

CU,
   Kai.

**Comment by Basster** [comment]
Hey Kai,
please try again. Should be working with SF4 now. Really surprised, that you are still using this bundle! :+1:

**Comment by kszyma** [comment]
Hi Ole,

thanks...you make my day...and surprise: Its a monday  ;)
